### ISSUE TITLE
dbc.Checklist switch not displaying selected when True is set as default

### ISSUE THREAD

**Issue by yuorme** [facultyai/dash-bootstrap-components#357]
I'd like to use a dbc.Checklist(switch=True) and set the default value to be True. When I initialize the app, the switch returns True to the callback but **displays** as if it were False (gray - unchecked). Once toggled, the switch behaves as normal. See GIF.

![checklist-switch-bug](https://user-images.githubusercontent.com/7991877/80329446-58451c80-8810-11ea-83a6-afa83637b81a.gif)

My checklist code is below:

`dbc.Checklist(
    options=[
        {"label": "Plot Actual Deaths and Cases", "value": True}
    ],
    value=True, #BUG: Doesn't default to display selected on intialization
    id="actual-values-toggle",
    switch=True,
),`

**Comment by tcbegley** [comment]
Hi @yuorme 

Since `Checklist` allows for multiple selections, the `value` argument expects a list of values. If you change it to `value=[True]` that should fix the problem. Let me know if not.

**Comment by yuorme** [comment]
Hi @tcbegley, 

Really appreciate you getting back to me so quickly. Unfortunately, changing that line to `value=[True]` doesn't fix the issue for me. What happens now is that `True` is set as the default value but the switch no longer toggles between True and False.

![checklist-switch-bug](https://user-images.githubusercontent.com/7991877/80387154-4c8c4100-8876-11ea-9b73-88b690a20a33.gif)

I'm on the latest conda-forge version of dbc (0.9.2) and using relatively up to date versions of dash/plotly. Here is my conda environment.

![image](https://user-images.githubusercontent.com/7991877/80386696-bd7f2900-8875-11ea-9064-ecd31fc426b9.png)

**Comment by tcbegley** [comment]
> That does fix the issue!

Great! Glad to hear it.

> I guess my only suggestion is that the documentation in dbc.Input could be improved to show an example where True was selected by default.

Sure, always happy for help making the documentation better. What do you have in mind? It might be worth comparing to the [documentation](https://dash.plotly.com/dash-core-components) for [`dcc.Checklist`](https://dash.plotly.com/dash-core-components/checklist), whose interface `dbc.Checklist` deliberately replicates.

The relevant file is [this one](https://github.com/facultyai/dash-bootstrap-components/blob/master/docs/components_page/components/input.md), if you want to add a new example it should go in [here](https://github.com/facultyai/dash-bootstrap-components/tree/master/docs/components_page/components/input) then you can refer to it from the Markdown template. Hopefully it's relatively clear just by looking at what's already there. 

You can test the docs locally by installing the [requirements](https://github.com/facultyai/dash-bootstrap-components/blob/master/docs/requirements.txt) then running `run.py` in the `docs/` folder. You'll need to copy some of the examples into the `docs/` folder for it to work, see [here](https://github.com/facultyai/dash-bootstrap-components/blob/master/tasks.py#L90-L98) (sorry, I should automate the copying of those files for development).

FWIW I notice you have two switches in your screenshot, but you only had one option in the code snippet. I think the more idiomatic thing to do would likely be something like this where you use a single `Checklist` component to render both switches, then check for particular value in the list of checked values

```python
dbc.Checklist(
    options=[
        {"label": "Semi-log plot", "value": "semi-log"},
        {"label": "Plot Actual Deaths and Cases", "value": "actual-deaths"},
    ],
    value=True,
    id="actual-values-toggle",
    switch=True,
)
```

then in a callback you do something like

```python
@app.callback(..., [Input("actual-values-toggle", "value"), ...])
def do_a_thing(checked_values, ...):
    if "semi-log" in checked_values:
        # make semi-log plot
    if "actual-deaths" in checked_values:
        # plot actual deaths
```

**Comment by tcbegley** [comment]
Closing this now, feel free to reopen if you are still having problems.
