### ISSUE TITLE
deprecated warning

### ISSUE THREAD

**Issue by rraymondgh** [facultyai/dash-bootstrap-components#692]
- dash version: `2.0.0`
- dash-bootstrap-components version: `0.13.0`
- components affected by bug:

### What is happening?

```
dash_bootstrap_components/_table.py:5: UserWarning:


The dash_html_components package is deprecated. Please replace
`import dash_html_components as html` with `from dash import html`
```

### What should be happening?

All components are latest versions,  there should be no deprecated warning.

**Comment by tcbegley** [comment]
Thanks @rraymondgh. This is resolved in our v1 beta. You can install with

```
pip install dash-bootstrap-components==1.0.0b1
```

Check out the [preview docs](http://dbc-v1.herokuapp.com) and particularly the [migration guide](http://dbc-v1.herokuapp.com/migration-guide/). Lots more details [here](https://community.plotly.com/t/dash-bootstrap-components-v1-beta-release-available/56526).

**Comment by luchaoqi** [comment]
Same question here. I installed the v1 beta but the problem still persists.

**Comment by tcbegley** [comment]
Hi @luchaoqi 

Are you seeing the exact same error, specifically coming from `dash_bootstrap_components/_table.py`?

Can you confirm that you definitely have `1.0.0b1` installed?

```python
from dash_bootstrap_components import __version__
print(__version__)
```

If you can provide a minimal working example that would be very helpful.

**Comment by luchaoqi** [comment]
Hey @tcbegley 

I believe the version was exactly `1.0.0b1` when I did the upgrade using pip and I checked that with `pip show`.

However, the warnings are gone when I completely reinstall the package. 

Sorry for the confusion and keep up this great project!
